# Generated by Django 4.2.3 on 2023-07-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='phonenmber',
            new_name='phonenumber',
        ),
    ]
