# Generated by Django 4.2.3 on 2023-07-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_phonenmber_newuser_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='Commune',
            new_name='commune',
        ),
    ]
